config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/room/create', to: 'rooms#new'
  post '/room/create', to: 'rooms#create'

  resources :users do
    member do
      get :rooms
    end
  end
  resources :rooms do
    member do
      get :users
    end
  end
  resources :relationships, only: [:create, :destroy]

  namespace 'api' do
    namespace 'v1' do
      get '/rooms', to: 'rooms#index'
      get '/rooms/:id', to: 'rooms#show'
      patch '/rooms/:id', to: 'rooms#update'
      delete '/rooms/:id', to: 'rooms#destroy'
      resource :rooms

      get '/users', to: 'users#index'
      get '/users/:id', to: 'users#show'
      patch '/users/:id', to: 'users#update'
      delete '/users/:id', to: 'users#destroy'
      resource :users

      resource :relationships
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :active_relationships, class_name:  "Relationship",
           foreign_key: "room_id", dependent:   :destroy
  has_many :users, through: :active_relationships, source: :user
  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 256}
end

app/controllers/api/v1/rooms_controller.rb
module Api
  module V1
    class RoomsController < ApplicationController
      def index
        rooms = Room.all
        render json: {status: 'SUCCESS', message: 'Loaded Rooms', data: rooms}, status: :ok
      end

      def show
        rooms = Room.find(params[:id])
        render json: {status: 'SUCCESS', message: 'Loaded Rooms', data: rooms}, status: :ok
      end

      def create
        room = Room.new(room_params)
        if room.save
          render json: {status: 'SUCCESS', message: 'Room Created', data: room}, status: :ok
        else
          render json: {status: 'ERROR', message: 'Room Created Failed', data: room.errors}, status: :unprocessable_entity
        end
      end

      def destroy
        room = Room.find(params[:id]).destroy
        render json: {status: 'SUCCESS', message: 'Rooms Deleted', data: room}, status: :ok
      end

      def update
        room = Room.find(params[:id])
        if room.update_attributes(room_params)
          render json: {status: 'SUCCESS', message: 'Room Updated', data: room}, status: :ok
        else
          render json: {status: 'ERROR', message: 'Room Updated Failed', data: room.errors}, status: :unprocessable_entity
        end
      end

    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: [:new, :edit,
                                    :update, :create,
                                    :destroy]

  def new
    @room = Room.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def show
    @room = Room.find(params[:id])
  end

  def index
    @rooms = Room.paginate(page: params[:page])
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = "Room created!"
      redirect_to rooms_url(@room)
    else
      render 'new'
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      flash[:success] = "Room updated!"
      redirect_to rooms_url(@room)
    else
      render 'edit'
    end
  end

  def destroy
    Room.find(params[:id]).destroy
    flash[:success] = "Room deleted"
    redirect_to rooms_url
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<% provide(:title, "Edit Room") %>
<h1>Edit Room</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@room) do |f| %>
      <%= render 'shared/room_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/rooms/index.html.erb
<% provide(:title, 'All rooms') %>
<h1>All rooms</h1>

<%= will_paginate %>

<ul class="rooms">
  <% @rooms.each do |room| %>
    <li>
      <%= link_to room.name, room %>
      <% if current_user.admin? %>
        | <%= link_to "edit", edit_room_path(room) %>
        | <%= link_to "delete", room, method: :delete,
                      data: {confirm: "You sure?"} %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/rooms/new.html.erb
<% provide(:title, 'Create New Room') %>
<h1>Create New Room</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@room, url: room_create_path) do |f| %>
      <%= render 'shared/room_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.submit "Create new room", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<% provide(:title, @room.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @room.name %>
      </h1>
      <%= @room.description %>
      <h2> Joined people </h2>
      <% @room.users.each do |user| %>
        <li>
          <%= user.name %>
        </li>
      <% end %>

      <% if logged_in? %>
        <% if current_user.has_room?(@room) %>
          <%= render 'users/cancel_room' %>
        <% else %>
          <%= render 'users/book_room' %>
        <% end %>
      <% end %>
    </section>

  </aside>
</div>